# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend-memory:
    image: backend-memory
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5030:5030
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production